esphome:
  name: "only-sensor-2-th"
  friendly_name: "Only Sensor 2-TH"

esp8266:
  board: d1_mini

# Logging
logger:
  # baud_rate: 0
  logs:
    sensor: INFO
    binary_sensor: INFO
    text_sensor: INFO

# Home Assistant API
api:
  encryption:
    key: !secret ha_api_encryption_key
  # Can comment this to reboot with no API
  reboot_timeout: 0s

# OTA
ota:
  safe_mode: true
  password: !secret ota_pass
  port: 3232

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .corp.nowsci.com
  # Hotspot fallback
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_pass
captive_portal:

# Web server
web_server:
  port: 80
  version: 2
  include_internal: true
  ota: true
  local: true
  auth:
    username: !secret web_server_auth_user
    password: !secret web_server_auth_pass

switch:
  # Switch for toggling safe mode
  - platform: safe_mode
    name: "Use safe mode"
    id: use_safe_mode

button:
  # Restart
  - platform: restart
    name: "Restart"
    id: restart_os5

sensor:
  # Uptime sensor
  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-start
    update_interval: 60s

  # Temperature and Humidity
  - platform: dht
    pin: D7
    temperature:
      name: "Temperature"
      id: temperature
      filters:
        - offset: -1.0
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    humidity:
      name: "Humidity"
      id: humidity
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    update_interval: 10s
    model: DHT11
