# Home Assistant API encryption key
ha_api_encryption_key: ""

# Password for updating ESP devices over the air
ota_pass: ""

# Wifi AP mode u/p, only used if setup fails
wifi_ap_ssid: "OnlySensor"
wifi_ap_pass: "OnlySensorPassword"

# Authentication when visiting the Only Sensor device with a web browser directly
web_server_auth_user: "admin"
web_server_auth_pass: "WebServerPassword"

# Your Wi-Fi SSID and password
wifi_ssid: ""
wifi_password: ""
